apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  Chart.name }}
  namespace: {{  .Values.namespaceName  }}
spec:
  replicas: {{  .Values.image.replicaCount  }}
  selector:
    matchLabels:
      app: {{  Chart.name }}
  template:
    metadata:
      labels:
        app: {{  Chart.name }}
    spec:
      containers:
      - name: {{  Chart.name }}
        image: {{  .Values.image.repository  }}/{{  .Chart.name  }}:{{  .Values.image.tag  }}
        imagePullPolicy: {{  .Values.image.pullPolicy  }}
        resources:
          limits:
            memory: {{  quote .Values.resources.limits.memory  }}
            cpu: {{  quote .Values.resources.limits.CPU  }}
          requests:
            memory: {{  quote .Values.resources.requests.CPU  }}
            cpu: {{  quote .Values.resources.requests.CPU  }}
        ports:
        - containerPort: {{  .Values.resources.containerPort }}
        livenessProbe:
          httpGet:
            path: {{  .Values.resources.livenessProbePath }}
            port: {{  .Values.resources.containerPort }}
        readinessProbe:
          httpGet:
            path: {{  .Values.resources.readinessProbePath }}
            port: {{  .Values.resources.containerPort }}
