apiVersion: v1
kind: Service
metadata:
  name: {{  .Chart.Name  }}
  namespace: {{  .Values.namespaceName  }}
spec:
  selector:
    app: {{  .Chart.Name  }}
  ports:
    - protocol: {{  .Values.service.protocol  }}
      port: {{  required "A valid .Values.service.port entry required!" .Values.service.port }}
      {{- if .Values.service.targetPort  }}
      targetPort: {{  .Values.service.targetPort  }}
      {{  else  }}
      targetPort: {{  .Values.service.port  }}
      {{-  end  }}
  type: {{  .Values.service.type  }}
