# CI Pipeline for TechTrends Python App Update to Docker Hub

name: TechTrends - Package with Docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: 
      - 'main'
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker Metadata action
      uses: docker/metadata-action@v3
      id: meta
      with:
        # List of Docker images to use as base name for tags
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/techtrends
        # List of tags as key-value pair attributes
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=ref,event=branch        
        # Flavors to apply
        flavor: |
          latest=auto
        # List of custom labels
        labels: |
          maintainer=NigelP
          org.opencontainers.image.title=techtrends
          org.opencontainers.image.description=display and add new posts
          org.opencontainers.image.vendor=npcarnival    


    - name: Docker Login
      uses: docker/login-action@v1
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # Log out from the Docker registry at the end of a job
        logout: true


    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker Layers
      uses: actions/cache@v2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: /tmp/.buildx-cache
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-buildx-
        # The chunk size used to split up large files during upload, in bytes
        upload-chunk-size: 1024


